import{Analytics}from'@vercel/analytics/react';import Header from'./components/Header';import FlipAlbum from'./components/FlipAlbum';import ContactForm from'./components/ContactForm';import{drawingImages,modelImages,processSteps,services}from'./data';import{useReveal}from'./hooks/useReveal';
const Kicker=({children,light=false})=><p className={`section-kicker ${light?'light':''}`}>{children}</p>;
export default function App(){useReveal();const benefits=[['01','Specialized support','Professional services tailored to specific business needs.'],['02','Flexible engagement','Engage us for a single task, a project, or ongoing support.'],['03','Reliable delivery','We focus on accuracy, organization, communication, and quality.']];return <><a className="skip-link" href="#main">Skip to content</a><Header/><main id="main">
<section className="hero"><div className="hero-media"><img src="/assets/project-03.jpg" alt="Detailed structural steel building model" fetchPriority="high"/><div className="hero-shade"/></div><div className="hero-grid" aria-hidden="true"/><div className="hero-content reveal"><p className="eyebrow"><span/> Precision behind every project</p><h1>Specialized support.<br/><em>Built around your needs.</em></h1><p className="hero-copy">Engineering, steel detailing, accounting, administrative, and creative services for businesses and professionals who value reliable delivery.</p><div className="hero-actions"><a className="button button-primary" href="#contact">Discuss your project <span>↗</span></a><a className="text-link" href="#work">Explore our work <span>↓</span></a></div></div><div className="hero-foot"><span>Engineering</span><span>Steel Detailing</span><span>Business support</span><span>Creative</span></div></section>
<section className="intro section-pad reveal"><Kicker>What we do</Kicker><div className="intro-copy"><h2>The right expertise,<br/>exactly when you need it.</h2><p>RIJJID Technical Solutions provides dependable professional services tailored to your business, project, or operational needs. Choose one focused service or build ongoing support around your workflow.</p></div></section>
<section className="services section-pad" id="services"><div className="section-head reveal"><Kicker>Our services</Kicker><p className="section-note">Five disciplines. One reliable partner.</p></div><div className="service-list">{services.map(s=><article className="service-card reveal" key={s.number}><span className="service-no">{s.number}</span><div><h3>{s.title}</h3><p>{s.description}</p><ul>{s.items.map(item=><li key={item}>{item}</li>)}</ul></div><span className="service-icon">{s.icon}</span></article>)}</div></section>
<section className="work section-pad" id="work"><div className="work-head reveal"><div><Kicker light>Project album</Kicker><h2>3D <em>Models.</em></h2></div><p>Explore our structural steel and industrial models. Click the main image to flip continuously through the complete album.</p></div><FlipAlbum images={modelImages} altPrefix="RIJJID 3D structural model" dark/></section>
<section className="drawings section-pad" id="drawings"><div className="work-head reveal"><div><Kicker>Technical drawing album</Kicker><h2>2D Drawings.</h2></div><p>Browse all structural and miscellaneous drawing sheets extracted from the project set.</p></div><FlipAlbum images={drawingImages} altPrefix="RIJJID 2D structural drawing sheet"/></section>
<section className="process section-pad" id="process"><div className="section-head reveal"><Kicker>How it works</Kicker><p className="section-note">Simple. Flexible. Focused.</p></div><div className="process-grid">{processSteps.map(([n,t,c])=><article className="reveal" key={n}><span>{n}</span><h3>{t}</h3><p>{c}</p></article>)}</div></section>
<section className="about section-pad" id="about"><div className="about-visual reveal"><img src="/assets/project-10.jpg" alt="Detailed industrial processing facility model" loading="lazy"/><span className="image-tag">Accuracy / Organization / Quality</span></div><div className="about-copy reveal"><Kicker>Why RIJJID</Kicker><h2>Professional support that fits the way you work.</h2><p>Our goal is simple: provide reliable specialized support so you can focus on your core business.</p>{benefits.map(([n,t,c])=><div className="benefit" key={n}><span>{n}</span><div><h3>{t}</h3><p>{c}</p></div></div>)}</div></section>
<section className="founder section-pad" id="founder"><div className="founder-portrait reveal"><div className="founder-frame"><img src="/assets/joshua-suangco.png" alt="Joshua M. Suangco, Founder and CEO of RIJJID Technical Solutions" loading="lazy"/></div><span className="founder-mark" aria-hidden="true">R</span></div><div className="founder-copy reveal"><Kicker light>Meet the Founder &amp; CEO</Kicker><h2>Joshua M.<br/><em>Suangco.</em></h2><p className="founder-role">Founder &amp; Chief Executive Officer <span/> Structural / Civil Engineer</p><div className="founder-story"><p>Joshua M. Suangco is a Structural/Civil Engineer with professional experience across engineering, construction, digital technologies, technical services, and professional training.</p><p>As the Founder and CEO of RIJJID Technical Solutions, Joshua leads the company with a vision of providing practical, reliable, and technology-driven solutions across a wide range of professional and technical needs.</p><p>His engineering background includes structural engineering, steel detailing, BIM, 3D modeling, construction documentation, site engineering, and engineering software training. His experience also includes structural and miscellaneous steel modeling, connection modeling, GA and assembly drawings, shop drawings, CNC-ready files, structural analysis, and construction-related engineering work.</p><p>At RIJJID Technical Solutions, this technical foundation serves as a starting point—not a limitation. The company is built to provide diverse solutions and services that help businesses, professionals, and organizations improve their workflows, solve technical challenges, and bring ideas into reality.</p></div></div></section>
<section className="contact section-pad" id="contact"><div className="contact-copy reveal"><Kicker light>Ready to get started?</Kicker><h2>Tell us what<br/><em>you need.</em></h2><p>Whether you need technical support, steel detailing, bookkeeping, administrative assistance, or creative services, let’s define the right next step.</p></div><ContactForm/></section>
</main><footer><a className="footer-brand" href="#top"><img src="/assets/logo.png" alt=""/><span>RIJJID Technical Solutions</span></a><p>Engineering. Steel Detailing. Accounting.<br/>Administrative. Creative.</p><div><a href="#services">Services</a><a href="#work">3D Models</a><a href="#drawings">2D Drawings</a><a href="#about">About</a><a href="#founder">Founder</a></div><small>© {new Date().getFullYear()} RIJJID Technical Solutions</small></footer><Analytics/></>}
