export const services=[
['01','Engineering & Construction','Technical support for engineering and construction requirements—from estimating to coordinated documentation.',['Engineering support','Quantity takeoffs & estimating','Construction documentation','Drawing coordination','Project support'],'⌁'],
['02','Detailing','Accurate drafting, modeling, and detailing support for fabrication and construction.',['Structural steel detailing','CAD drafting & 3D modeling','Shop & fabrication drawings','Construction drawings','Drawing revisions'],'◇'],
['03','Accounting & Bookkeeping','Organized bookkeeping and financial administrative support that keeps your records in order.',['Bookkeeping & data entry','Accounts payable & receivable','Expense tracking','Invoice preparation','Spreadsheet management'],'▥'],
['04','Administrative Support','Dependable day-to-day support that helps businesses and professionals stay organized.',['Email & calendar management','Meeting coordination','Document & report preparation','Research and file organization','Client & vendor coordination'],'≡'],
['05','Creative Services','Professional creative support to help your business communicate clearly and present itself effectively.',['Logo & brand identity','Marketing materials','Social media graphics','Presentation design','Promotional materials'],'✦']].map(([number,title,description,items,icon])=>({number,title,description,items,icon}));
const titles=['Structural systems','Commercial steel structure','Multi-level steel frame','Architectural steel model','Coordinated building frame','Grandstand structure','Industrial facility','Process plant model','Long-span grandstand','Processing tower','Material handling structure'];export const projects=titles.map((title,index)=>({id:index+1,title,category:index<7?'Structural steel detailing':'Industrial modeling',image:`/assets/project-${String(index+1).padStart(2,'0')}.jpg`}));export const processSteps=[['01','Choose your service','Tell us what type of support you need.'],['02','Discuss requirements','Share your project, tasks, files, and priorities.'],['03','Define the scope','We determine the right deliverables and engagement.'],['04','Get the support','RIJJID delivers the service you requested.']]
export const modelImages=projects.map(project=>project.image)
export const drawingImages=Array.from({length:31},(_,index)=>`/drawings/drawing-${String(index+1).padStart(3,'0')}.jpg`)
